# Generated by Django 6.0 on 2025-12-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allowed_discounts',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed discount percentages (e.g., [5, 7, 10])'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
