# Generated by Django 6.0 on 2025-12-16 00:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_category_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='applied_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='allowed_discounts',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Global Order Discount %', max_digits=5),
        ),
    ]
